#!/bin/bash
#
# hadoop-namenode
#
# Author:       Eugene Koontz <ekoontz@hiro-tan.org>
#
# Description:  Hadoop Namenode Daemon
#               Intended to work well with Puppet and Amazon EC2: 
#               see: 
#                 http://github.com/ekoontz/hbase-ec2/blob/puppet/lib/puppet/manifests/site.pp

# source function library

. /lib/lsb/init-functions

RETVAL=0
#fixme: use system env.
export JAVA_HOME=/opt/jre1.6.0_22
export PATH=$JAVA_HOME/bin:$PATH
export HADOOP_USER=ec2-user

start() {
	sudo -u $HADOOP_USER JAVA_HOME=$JAVA_HOME /opt/hadoop-common/bin/hadoop-daemon.sh start namenode
	RETVAL=$?
	echo
}

stop() {
	start-stop-daemon --chuid $HADOOP_USER --exec /opt/hadoop-common/bin/hadoop-daemon.sh --start -- stop namenode
	echo
}

restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop) 
	stop
	;;
  restart|force-reload|reload)
	restart
	;;
  *)
	echo $"Usage: $0 {start|stop|status|restart}"
	exit 1
esac

exit $RETVAL
