#!/bin/bash
#
# hbase-regionserver
#
# Author:       Eugene Koontz <ekoontz@hiro-tan.org>
#
# Description:  Hbase Regionserver Daemon
#               Intended to work well with Puppet and Amazon EC2: 
#               see: 
#                 http://github.com/ekoontz/hbase-ec2/blob/puppet/lib/puppet/manifests/site.pp

# source function library
. /etc/rc.d/init.d/functions

RETVAL=0
#fixme: use system env.
export JAVA_HOME=/opt/jre1.6.0_22
export PATH=$JAVA_HOME/bin:$PATH
export HBASE_USER=ec2-user

start() {
	daemon --user=$HBASE_USER '/opt/hbase/bin/hbase-daemon.sh start regionserver'
	RETVAL=$?
	echo
}

stop() {
	daemon --user=$HBASE_USER '/opt/hbase/bin/hbase-daemon.sh stop regionserver'
	echo
}

restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop) 
	stop
	;;
  restart)
	restart
	;;
  *)
	echo $"Usage: $0 {start|stop|status|restart}"
	exit 1
esac

exit $RETVAL
