#!/bin/bash
#
# hbase-regionserver
#
# Author:       Eugene Koontz <ekoontz@hiro-tan.org>
#
# Description:  Hbase Regionserver Daemon
#               Intended to work well with Puppet and Amazon EC2: 
#               see: 
#                 http://github.com/ekoontz/hbase-ec2/blob/puppet/lib/puppet/manifests/site.pp

RETVAL=0
#fixme: use system env.
export JAVA_HOME=/opt/jre1.6.0_22
export PATH=$JAVA_HOME/bin:$PATH
export HBASE_USER=ec2-user

set -x
start() {
	sudo -u $HBASE_USER JAVA_HOME=$JAVA_HOME /opt/hbase/bin/hbase-daemon.sh start regionserver
	RETVAL=$?
	echo
}

stop() {
	sudo -u $HBASE_USER JAVA_HOME=$JAVA_HOME /opt/hbase/bin/hbase-daemon.sh stop regionserver
	echo
}

restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop) 
	stop
	;;
  restart)
	restart
	;;
  *)
	echo $"Usage: $0 {start|stop|status|restart}"
	exit 1
esac

exit $RETVAL
