#!/bin/bash
#
# chkconfig: 345 55 25
# lily_server
#
# Author:       Eugene Koontz <ekoontz@hiro-tan.org>
#
# Description:  Lily: The Scalable Content Repository
#               Intended to work well with Puppet and Amazon EC2: 
#               see: 
#                 http://github.com/ekoontz/hbase-ec2/blob/puppet/lib/puppet/manifests/site.pp

RETVAL=0

set -x

export JAVA_HOME=/opt/jre1.6.0_22
export HADOOP_USER=ec2-user
export HADOOP_CLASSPATH=/opt/hadoop-common/build/hadoop-core-0.20.104.3-append-SNAPSHOT.jar
start() {
#	sudo -u $HADOOP_USER JAVA_HOME=$JAVA_HOME HADOOP_CLASSPATH=$HADOOP_CLASSPATH /opt/hadoop-common/bin/hadoop-daemon.sh start namenode
	RETVAL=$?
	echo
}

stop() {
#	sudo -u $HADOOP_USER JAVA_HOME=$JAVA_HOME /opt/hadoop-common/bin/hadoop-daemon.sh stop namenode
	echo
}

restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop) 
	stop
	;;
  restart|force-reload|reload)
	restart
	;;
  *)
	echo $"Usage: $0 {start|stop|status|restart}"
	exit 1
esac

exit $RETVAL
