#!/bin/bash
#
# chkconfig: 345 55 25
# zookeeper-quorum-member
#
# Author:       Eugene Koontz <ekoontz@hiro-tan.org>
#
# Description:  Zookeeper Quorum Member Daemon
#               Intended to work well with Puppet and Amazon EC2: 
#               see: 
#                 http://github.com/ekoontz/hbase-ec2/blob/puppet/lib/puppet/manifests/site.pp

RETVAL=0
#fixme: use system env.
export JAVA_HOME=/opt/jre1.6.0_22
export PATH=$JAVA_HOME/bin:$PATH
export ZOOKEEPER_USER=ec2-user
export CLASSPATH=/opt/zookeeper/build/zookeeper-3.4.0.jar

start() {
        sudo -u $ZOOKEEPER_USER JAVA_HOME=$JAVA_HOME CLASSPATH=$CLASSPATH PATH=$JAVA_HOME/bin:$PATH /opt/zookeeper/bin/zkServer.sh start
	RETVAL=$?
	echo
}

stop() {
        sudo -u $ZOOKEEPER_USER JAVA_HOME=$JAVA_HOME /opt/zookeeper/bin/zkServer.sh stop
	echo
}

restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop) 
	stop
	;;
  restart|force-reload|reload)
	restart
	;;
  *)
	echo $"Usage: $0 {start|stop|status|restart}"
	exit 1
esac

exit $RETVAL
